### ISSUE TITLE
Credit Cards (Pre-Ynab Debt)

### ISSUE THREAD

**Issue by ShoGinn** [rixx/ynab-downgrade#5]
I just wanted to point out that creating accounts before imported categories is not the best way.

If you create accounts (and have a ton of accounts [been using ynab since 2014]) especially credit cards.

It creates a "Pre YNAB Debt"

Because of that category, when you import categories it deletes all of them and then omits them from the category list.

This causes an error when you load the budget (its even logged as such).

The fix action is to just to create a new budget in ynab4, then import categories, then create accounts, then import transactions!

Just wanted to throw that out for those out there!

I have created a pull request #6

**Comment by DeeeeLAN** [comment]
I had no issues creating my accounts first, it just created duplicate categories. The master categories for each must have had different names or something.

**Comment by rixx** [comment]
Should be fixed via #6 in any case.
